### ISSUE TITLE
All buttons appear on the corner of the screen

### ISSUE THREAD

**Issue by jufryananta** [aloeguvner/rpg-maker-mv#3]
When all buttons are hidden. they disappear completely. but after a conversation occurs, all buttons are seen piled on the corner of the screen.
![untitled](https://user-images.githubusercontent.com/9709267/46059301-d058e580-c188-11e8-8fce-9575494afee7.jpg)

**Comment by aloeguvner** [comment]
I was not able to recreate this issue after some testing.

When you say "When all buttons are hidden", is this through a plugin command or some other method? If it's a plugin command, can you share the relevant contents of the event that is using those plugin commands?

**Comment by aloeguvner** [comment]
I believe I found the error, if the player chooses to hide the buttons by pressing the "Control Button", then everything re-appears after a conversation.

I fixed it by having the plugin remember that the player chose to hide the buttons by pressing the "Control Button", and so those hidden buttons won't re-appear after a conversation.
